export const SCORE__ICON = "💯";
export const MEDAL__ICON = "🥇";
export const MINUS__BTN = "-";
export const PLUS__BTN = "+";
export const CHECK__BTN = "check";
export const RETRY__BTN = "Retry";
export const ANSWER__RANGE__TEXT = "(Between 1 and 10)";
export const QUESTION__MARK = "?";
export const START_TEXT = "Start guessing...";
